name: Sync
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#*/0 * * * *
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # - name: sync github api
      #   uses: google/secrets-sync-action@v1.1.3
      #   with:
      #     SECRETS: |
      #       ^SYNCED_
      #     REPOSITORIES: |
      #       ^guitarrapc/Base64UrlCore
      #     GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
      #     DRY_RUN: false
      #   env:
      #     SYNCED_GITHUB_TOKEN_REPO: ${{ secrets.GITHUBTOKEN_REPO }}
      - name: sync nuget key
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/AgonesPod
            ^guitarrapc/AgonesSdkCsharp
            ^guitarrapc/Base64UrlCore
            ^guitarrapc/CsProjEditor
            ^guitarrapc/DirectoryPropSwitch
            ^guitarrapc/KustomizeConfigMapGenerator
            ^guitarrapc/MySQLQueryDivider
            ^guitarrapc/SkiaSharp.QrCode
            ^guitarrapc/TeamsId2BitwardenConverter
            ^guitarrapc/UnityBuildRunner
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          # no synchronization
          #SYNCED_RUN_ID: ${{ github.run_id }}
          SYNCED_NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - name: sync docker user/pass
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/AgonesPod
            ^guitarrapc/docker.*
            ^guitarrapc/dotnet-lab
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_DOCKER_USER: ${{ secrets.DOCKER_USER }}
          SYNCED_DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      - name: sync powershell nuget
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/ScoopPlaybook
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_PSGALLERY_NUGET_KEY: ${{ secrets.PSGALLERY_NUGET_KEY }}
