name: Sync
on:
  schedule:
    # https://crontab.guru/#*/10_*_*_*_*
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync nuget key
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/Base64UrlCore
            ^guitarrapc/CsProjEditor
            ^guitarrapc/UnityBuildRunner
            ^guitarrapc/KustomizeConfigMapGenerator
            ^guitarrapc/TeamsId2BitwardenConverter
            ^guitarrapc/SkiaSharp.QrCode
            ^guitarrapc/MySQLQueryDivider
            ^guitarrapc/AgonesSdkCsharp
            ^guitarrapc/AgonesPod
            ^guitarrapc/DirectoryPropSwitch
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          #SYNCED_RUN_ID: ${{ github.run_id }}
          SYNCED_GITHUB_TOKEN_REPO: ${{ secrets.GITHUBTOKEN_REPO }}
          SYNCED_NUGET_KEY: ${{ secrets.NUGET_KEY }}
      - name: sync docker user/pass
        uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/docker.*
            ^guitarrapc/AgonesPod
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_DOCKER_USER: ${{ secrets.DOCKER_USER }}
          SYNCED_DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
