name: Sync
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#0_0_*_*_1
    - cron: "0 0 * * 1"
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync github api
        uses: jpoehnelt/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/AgonesSample
            ^guitarrapc/docker-aws-cli
            ^guitarrapc/docker-bicep
            ^guitarrapc/docker-ubuntu-mingw-w64
            ^guitarrapc/githubactions-lab
            ^guitarrapc/SkiaSharp.QrCode
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_GITHUB_TOKEN_REPO: ${{ secrets.GITHUBTOKEN_REPO }}
          
      - name: sync nuget key
        uses: jpoehnelt/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/AgonesPod
            ^guitarrapc/AgonesSdkCsharp
            ^guitarrapc/Base64UrlCore
            ^guitarrapc/CsProjEditor
            ^guitarrapc/DirectoryPropSwitch
            ^guitarrapc/KustomizeConfigMapGenerator
            ^guitarrapc/MySQLQueryDivider
            ^guitarrapc/SkiaSharp.QrCode
            ^guitarrapc/TeamsId2BitwardenConverter
            ^guitarrapc/UnityBuildRunner
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          # no synchronization
          #SYNCED_RUN_ID: ${{ github.run_id }}
          SYNCED_NUGET_KEY: ${{ secrets.NUGET_KEY }}
          
      - name: sync docker user/pass
        uses: jpoehnelt/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/AgonesPod
            ^guitarrapc/AgonesSample
            ^guitarrapc/csharp-lab
            ^guitarrapc/docker.*
            ^guitarrapc/dotnet-lab
            ^guitarrapc/go-lab
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_DOCKER_USER: ${{ secrets.DOCKER_USER }}
          SYNCED_DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
          
      - name: sync powershell nuget
        uses: jpoehnelt/secrets-sync-action@v1.4.1
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/ScoopPlaybook
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
          DRY_RUN: false
        env:
          SYNCED_PSGALLERY_NUGET_KEY: ${{ secrets.PSGALLERY_NUGET_KEY }}
