name: Sync

on:
  schedule:
    # https://crontab.guru/#*/10_*_*_*_*
    - cron: "*/10 * * * *"
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.1.3
        with:
          SECRETS: |
            ^SYNCED_
          REPOSITORIES: |
            ^guitarrapc/\w.*
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN_REPO }}
        env:
          SYNCED_RUN_ID: ${{ github.run_id }}
          SYNCED_GITHUB_TOKEN_REPO: ${{ secrets.GITHUBTOKEN_REPO }}
          SYNCED_DOCKER_KEY: ${{ secrets.DOCKER_KEY }}
          SYNCED_DOCKER_USER: ${{ secrets.DOCKER_USER }}
          SYNCED_NUGET_KEY: ${{ secrets.NUGET_KEY }}
